version: '3.3'

services:
  todo_dev_be:
    build: ${PWD}/docker/dev
    container_name: todo_dev_be
    hostname: todo_dev_be
    ports:
      - 3333:3333
      - 3330:3330
    tty: true
    volumes:
      - ./:/app/
    depends_on:
      - todo_mongo
  todo_dev_fe:
    build: ${PWD}/docker/dev
    container_name: todo_dev_fe
    hostname: todo_dev_fe
    ports:
      - 4200:4200
    tty: true
    volumes:
      - ./:/app/
  todo_mongo:
    image: mongo:4.4.6
    command: --serviceExecutor adaptive
    restart: always
    container_name: todo_mongo
    hostname: todo_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: 210Todo!707
  todo_proxy:
    image: nginx:1.19.10
    container_name: todo_proxy
    hostname: todo_proxy
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=todo.local
      - NGINX_PORT=80
    volumes:
      - ${PWD}/docker/nginx/nginx-develop.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
